# Shameless copy of @AlastairUK's fine work for the jpl_eph repo.
# Aside from the comment,  this is almost a byte-for-byte copy.
name: Build

on: [push, pull_request]

jobs:
  buildUbuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: make
      run: |
        git clone https://github.com/Bill-Gray/lunar
        cd lunar
        make ERRORS=Y liblunar.a
        make install
        cd ..
        make ERRORS=Y

  buildOSX:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: make
      run: |
        git clone https://github.com/Bill-Gray/lunar
        cd lunar
        make CC=clang ERRORS=Y liblunar.a
        make install
        cd ..
        make CC=clang ERRORS=Y

  buildWindows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: make
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        git clone https://github.com/Bill-Gray/lunar
        mkdir myincl
        cd lunar
        nmake -f lunar.mak lunar64.lib
        nmake -f lunar.mak install
        cd ..
        set CL=/I"./myincl"
        copy lunar\*.lib .
        nmake -f msvc.mak
      shell: cmd
